language: node_js
services:
- docker
- ntp
script:
- npm test
- docker-compose build
- docker-compose up -d
- sleep 5
- npm run-script integration-test
deploy:
  provider: npm
  email: clement.michaud34@gmail.com
  api_key:
    secure: IKRQQQmqpbWb42VKiL54pDHGGtpx4WmPCNSmcfxnF4gWK8OnzDYAO/KIEvZI8KWwuQCTCtAIb28eusYfQ1hMIDCpMNojgQ3cau/k3ivgojR7APjUuJYZqAuvyUPAHzLHSfFbSgKErW/ueTlQAPPsaRn7uxDC6zbnTLb0h4snwwp0pbpNQN446X6zbcEXcZI1RXBWX0guBy+D9t4b0oLkk8WmGheEzIXTn1FJLJZjB3/QESO5iwpDZDveTAxL1n5cxazeo/O8wdv6lgg3xlPF0UA+0fHO7LglNZdKb92AM5B04D4qkNgZ6iGrCYf+Ou7QGtaVaOvygTPa8m4rpbAuDl3rKCy2RVdWHxKWEMU0B1zv/8VdisdkYpXJjjYInxqqJ+dvHWthnVhHAeOFY5oBdJ3KBXCBI2r8SrPfwFh4hcBw9UmlU8AKTVTN+oduDFilHK77A6adzNsgZFfJC0Uoa57b2BobLhkbcsDMs7TSgIX8DsST7/5CcyMHbHkqKXi8keg1DDac/Hl2l1782iodz+ETr9+IEfJxBsWRO+4OmCUoEU6YzQCzOf4ve8RPEqyfeq9p0I35Q1y/ljUVpvRffuS3DHwMkPTVJfACG+cgvQKErmwbTOXXSDTsaW7shW7Xu3Wka3rVaIDxM6zlY9OuVGrHfRibb16FYIXgejWqB1w=
  on:
    tags: true
    repo: clems4ever/http-two-factor
notifications:
  email:
    recipients:
    - clement.michaud34@gmail.com
    on_success: change
    on_failure: always
