###############################################################
#                Authelia minimal configuration               #
###############################################################

ldap:
  url: ldap://openldap
  base_dn: dc=example,dc=com

  additional_users_dn: ou=users
  additional_groups_dn: ou=groups
  
  groups_filter: (&(member={dn})(objectclass=groupOfNames))
  
  user: cn=admin,dc=example,dc=com
  password: password

session:
  # The secret to encrypt the session cookies.
  secret: unsecure_session_secret

  # The domain to protect.
  # Note: the authenticator must also be in that domain. If empty, the cookie
  # is restricted to the subdomain of the issuer. 
  domain: example.com
