
# The port to listen on
port: 8080

# Level of verbosity for logs
logs_level: info

# Configuration of LDAP
# Example: for user john, the DN will be cn=john,ou=users,dc=example,dc=com
ldap:
  url: ldap://ldap
  user_search_base: ou=users,dc=example,dc=com
  user_search_filter: cn
  user: cn=admin,dc=example,dc=com
  password: password


# Configuration of session cookies
#
# _secret_ the secret to encrypt session cookies
# _expiration_ the time before cookies expire
# _domain_ the domain to protect. 
# Note: the authenticator must also be in that domain. If empty, the cookie
# is restricted to the subdomain of the issuer. 
session:
  secret: unsecure_secret
  expiration: 3600000
  domain: example.com


# The directory where the DB files will be saved
store_directory: /var/lib/auth-server/store


# Notifications are sent to users when they require a password reset, a u2f
# registration or a TOTP registration.
# Use only one available configuration: filesystem, gmail
notifier:
  # For testing purpose, notifications can be sent in a file
  filesystem:
    filename: /var/lib/auth-server/notifications/notification.txt

  # Use your gmail account to send the notifications. You can use an app password.
  # gmail:
  #   username: user@example.com
  #   password: yourpassword
  
