
debug_level: info

ldap:
  url: ldap://ldap
  base_dn: ou=users,dc=example,dc=com
  user: cn=admin,dc=example,dc=com
  password: password

session:
  secret: unsecure_secret
  expiration: 3600000

store_directory: /var/lib/auth-server

notifier:
  gmail:
    username: user@example.com
    password: yourpassword
  
