
version: '2'
services:
  auth-server:
    build: .
    environment:
      - LDAP_URL=ldap://ldap
      - LDAP_USERS_DN=dc=example,dc=com
      - TOTP_SECRET=NBD2ZV64R7UV1O7K
      - JWT_SECRET=unsecure_secret
      - JWT_EXPIRATION_TIME=1h
      - PORT=80
    depends_on:
      - ldap
    expose:
      - "80"

  ldap:
    image: osixia/openldap:1.1.7
    environment:
      - LDAP_ORGANISATION=MyCompany
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=test
    expose:
      - "389"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/index.html:/usr/share/nginx/html/index.html
      - ./nginx_conf/secret.html:/usr/share/nginx/html/secret.html
    depends_on:
      - auth-server
    ports:
      - "8085:80"
