
version: '2'
services:
  auth:
    build: .
    depends_on:
      - ldap
    restart: always
    volumes:
     - ./config.yml:/etc/auth-server/config.yml:ro

  ldap:
    image: dinkel/openldap
    environment:
      - SLAPD_ORGANISATION=MyCompany
      - SLAPD_DOMAIN=example.com
      - SLAPD_PASSWORD=password
    expose:
      - "389"
    volumes:
      - ./example/ldap:/etc/ldap.dist/prepopulate

  nginx:
    image: nginx:alpine
    volumes:
      - ./example/nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./example/nginx_conf/index.html:/usr/share/nginx/html/index.html
      - ./example/nginx_conf/secret.html:/usr/share/nginx/html/secret.html
      - ./example/nginx_conf/ssl:/etc/ssl
    depends_on:
      - auth
    ports:
      - "8080:443"
