
version: '2'
services:
  auth:
    build: .
    environment:
      - LDAP_URL=ldap://ldap
      - LDAP_USERS_DN=dc=example,dc=com
      - TOTP_SECRET=GRWGIJS6IRHVEODVNRCXCOBMJ5AGC6ZE
      - JWT_SECRET=unsecure_secret
      - JWT_EXPIRATION_TIME=1h
    depends_on:
      - ldap
    restart: always

  ldap:
    image: osixia/openldap:1.1.7
    environment:
      - LDAP_ORGANISATION=MyCompany
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=password
    expose:
      - "389"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_conf/index.html:/usr/share/nginx/html/index.html
      - ./nginx_conf/secret.html:/usr/share/nginx/html/secret.html
    depends_on:
      - auth
    ports:
      - "8080:80"
