version: '2'
services:
  authelia:
    build: .
    restart: always
    volumes:
      - ./config.template.yml:/etc/authelia/config.yml:ro
    depends_on: 
      - redis
    networks:
      - example-network
