version: '2'
services:
  authelia:
    build: .
    restart: always
    volumes:
      - ./config.template.yml:/etc/authelia/config.yml:ro
      - ./notifications:/var/lib/authelia/notifications
    networks:
      - example-network

  redis:
    image: redis
    networks:
      - example-network
