
version: '2'
services:
  auth:
    volumes:
      - ./test:/usr/src/test
      - ./dist/src/server:/usr/src
      - ./node_modules:/usr/src/node_modules
      - ./config.yml:/etc/auth-server/config.yml:ro

