
version: '2'
services:
  auth:
    volumes:
      - ./test:/usr/src/test
      - ./src/views:/usr/src/views
      - ./src/public_html:/usr/src/public_html

  ldap-admin:
    image: osixia/phpldapadmin:0.6.11
    ports:
      - 9090:80
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap 
      - PHPLDAPADMIN_HTTPS=false
