version: '2'
services:
  openldap:
    build: ./example/ldap
    volumes:
      - ./example/ldap/base.ldif:/etc/ldap.dist/prepopulate/base.ldif
      - ./example/ldap/access.rules:/etc/ldap.dist/prepopulate/access.rules
    networks:
      - example-network

