#!/usr/bin/env bash

set +u

declare -A BUILDS=(["linux"]="amd64 arm32v7 arm64v8" ["freebsd"]="amd64")
DOCKER_IMAGE=authelia/authelia

if [[ "${BUILDKITE_LABEL}" == ":hammer_and_wrench: Unit Test" ]]; then
  find . -maxdepth 1 -name "authelia-linux-arm" -exec bash -c 'mv $0 ${0/arm/arm32v7}' {} \;
  find . -maxdepth 1 -name "authelia-linux-arm64" -exec bash -c 'mv $0 ${0/arm64/arm64v8}' {} \;

  echo "--- :docker: Saving artifacts for :buildkite: :docker: :github: releases"
  for OS in "${!BUILDS[@]}"; do
    for ARCH in ${BUILDS[$OS]}; do
      tar -czf "authelia-${OS}-${ARCH}.tar.gz" "authelia-${OS}-${ARCH}" authelia.service config.template.yml
      sha256sum "authelia-${OS}-${ARCH}.tar.gz" > "authelia-${OS}-${ARCH}.tar.gz.sha256"
    done
  done

  tar -czf authelia-public_html.tar.gz -C dist public_html
  sha256sum authelia-public_html.tar.gz > authelia-public_html.tar.gz.sha256
fi

if [[ "${BUILDKITE_LABEL}" =~ ":docker: Build Image" ]]; then
  # Saving image for docker push
  docker save "${DOCKER_IMAGE}" | zstdmt -T0 -12 > "authelia-image-${ARCH}.tar.zst"
fi

if [[ "${BUILDKITE_LABEL}" =~ ":debian: Build Package" ]]; then
  if [[ "${BUILDKITE_TAG}" != "" ]]; then
    echo "--- :debian: Saving artifacts for :github: release"
    for f in *.deb; do mv "$f" "$(echo "$f" | sed s/${BUILDKITE_TAG//v}-1_//)"; done
  else
    echo "--- :debian: Saving artifacts for :buildkite: release"
    VERSION=$(git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g')
    for f in *.deb; do mv "$f" "$(echo "$f" | sed s/${VERSION}-1_//)"; done
  fi
  sha256sum "authelia_${PACKAGE}.deb" > "authelia_${PACKAGE}.deb.sha256"
fi