---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authelia
  labels:
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/name: authelia
data:
  configuration.yaml: |
    # Obtain the configuration template content from https://github.com/authelia/authelia/blob/master/config.template.yml
...
